from .main import *
from .upload_data import *
from .signup import *
from .pass_reset import *
from .all_std import *
from .reg_std import *
from .dashboard import *
from .cancel_reg import *
from .email_conf_send import *
from .rank_upload import *