# Generated by Django 3.0.3 on 2020-02-13 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=99999)),
                ('sID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('gender', models.CharField(default='none', max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('shift', models.CharField(default='none', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sec_email', models.CharField(default='none', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sec_phone', models.CharField(default='none', max_length=100)),
                ('status', models.CharField(default='Not_Registered', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancel_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=99999)),
                ('sID', models.CharField(max_length=30)),
                ('email', models.CharField(default='none', max_length=100)),
                ('phone', models.CharField(default='none', max_length=100)),
                ('cancel_by', models.CharField(default='none', max_length=100)),
                ('cancel_time', models.DateTimeField(auto_now_add=True)),
                ('req_by', models.CharField(default='none', max_length=100)),
                ('req_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=99999)),
                ('sID', models.CharField(max_length=30)),
                ('t_shirt', models.CharField(default='none', max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('pc_no', models.CharField(max_length=100)),
                ('userid', models.CharField(default='none', max_length=100)),
                ('password', models.CharField(default='none', max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('solve', models.IntegerField(default=99)),
                ('penalty', models.IntegerField(default=99999)),
                ('advance_camp', models.CharField(default='Pending', max_length=100)),
                ('regby', models.CharField(max_length=100)),
                ('regtiem', models.DateTimeField(auto_now_add=True)),
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TOPC_Reg_SYS.ALLStudents')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('shift', models.CharField(default='none', max_length=100)),
                ('email', models.CharField(default='none', max_length=100)),
                ('phone', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Req_queuey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=99999)),
                ('req_by', models.CharField(default='none', max_length=100)),
                ('req_time', models.DateTimeField(auto_now_add=True)),
                ('req_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TOPC_Reg_SYS.RegStudents')),
            ],
        ),
    ]
