# Generated by Django 3.0.2 on 2020-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('regby', models.CharField(max_length=100)),
                ('regtiem', models.DateTimeField()),
                ('status', models.CharField(default='Not_Registered', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('pc_no', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('solve', models.IntegerField(default=99)),
                ('penalty', models.IntegerField(default=99)),
                ('advance_camp', models.CharField(default='Pending', max_length=100)),
                ('regby', models.CharField(max_length=100)),
                ('regtiem', models.DateTimeField()),
                ('reg_status', models.CharField(default='Not_Registered', max_length=100)),
            ],
        ),
    ]
