# Generated by Django 3.0.3 on 2020-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_info',
            name='email',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='phone',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
