# Generated by Django 3.0.3 on 2020-02-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roon_no', models.CharField(max_length=30)),
                ('token_starts', models.IntegerField(default=99999)),
                ('token_ends', models.IntegerField(default=99999)),
                ('total_pcs', models.IntegerField(default=99999)),
                ('generated_by', models.CharField(default='none', max_length=100)),
                ('M_count', models.IntegerField(default=0)),
                ('L_count', models.IntegerField(default=0)),
                ('XL_count', models.IntegerField(default=0)),
                ('XXL_count', models.IntegerField(default=0)),
                ('XXXL_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='regstudents',
            name='viva_date',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
