# Generated by Django 3.0.3 on 2020-02-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0002_auto_20200210_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudents',
            name='t_shirt',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
