# Generated by Django 3.0.3 on 2020-02-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0003_allstudents_t_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='regstudents',
            name='t_shirt',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
