# Generated by Django 3.0.3 on 2020-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0004_regstudents_t_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='regstudents',
            name='token',
            field=models.IntegerField(default=99999),
        ),
    ]
