# Generated by Django 3.0.3 on 2020-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0005_regstudents_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudents',
            name='token',
            field=models.IntegerField(default=99999),
        ),
    ]
