# Generated by Django 3.0.3 on 2020-02-12 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0007_auto_20200211_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('shift', models.CharField(default='none', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='allstudents',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='allstudents',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='allstudents',
            name='regby',
        ),
        migrations.RemoveField(
            model_name='allstudents',
            name='regtiem',
        ),
        migrations.RemoveField(
            model_name='allstudents',
            name='solve',
        ),
        migrations.RemoveField(
            model_name='allstudents',
            name='t_shirt',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='department',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='reg_status',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='section',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='regstudents',
            name='shift',
        ),
        migrations.AddField(
            model_name='allstudents',
            name='sec_email',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='allstudents',
            name='sec_phone',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='regstudents',
            name='basic_info',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='TOPC_Reg_SYS.ALLStudents'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Req_queuey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=99999)),
                ('req_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TOPC_Reg_SYS.RegStudents')),
            ],
        ),
    ]
