# Generated by Django 3.0.3 on 2020-02-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOPC_Reg_SYS', '0008_auto_20200212_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regstudents',
            name='regtiem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
